import functools
import inspect
import logging
import re
from collections.abc import Callable, Mapping, Sequence
from enum import Enum
from hashlib import sha1
from math import isinf, isnan
from types import FunctionType, UnionType
from typing import (
    Annotated,
    Any,
    Union,
    get_args,
    get_origin,
    get_type_hints,
)

from spectree._types import (
    ModelAdapterType,
    MultiDict,
    MultiDictStarlette,
    NamingStrategy,
)
from spectree.metadata import FunctionDecorator
from spectree.model_adapter import ModelClass

# parse HTTP status code to get the code
HTTP_CODE = re.compile(r"^HTTP_(?P<code>\d{3})$")

cached_type_hints = functools.cache(get_type_hints)


logger = logging.getLogger(__name__)


def parse_comments(func: Callable[..., Any]) -> tuple[str | None, str | None]:
    """Parse function docstring into a summary and description string.

    The first few lines of the docstring up to the first empty line will be extracted
    as the summary, and the rest of the docstring, following the empty line will become
    the description.

    If the function's docstring also contains parameter documentation, you can avoid
    parsing it as part of the summary or description by prefixing it with the `"\\\\f"`
    form feed character. Everything after the `"\\\\f"` character will be ignored in the
    docstring.

    :param func: The callable whose docstring should be parsed.
    :returns: A two element tuple with the summary and the description strings.
    """
    docstring = inspect.getdoc(func)
    if docstring is None:
        return None, None

    docstring = re.split("\f", docstring, maxsplit=1)[0]

    docstring_parts = re.split(r"\n\s*\n", docstring)
    for i in range(len(docstring_parts)):
        docstring_parts[i] = docstring_parts[i].rstrip()
        docstring_parts[i] = docstring_parts[i].replace("\n", " ")

    summary = docstring_parts[0]
    description = None
    if len(docstring_parts) > 1:
        description = "\n\n".join(docstring_parts[1:])

    return summary, description


def parse_request(metadata: FunctionDecorator) -> dict[str, Any]:
    """
    get json spec
    """
    return metadata.parse_request()


def parse_params(
    metadata: FunctionDecorator,
    params: list[Mapping[str, Any]],
    models: Mapping[str, Any],
) -> list[Mapping[str, Any]]:
    """
    get spec for (query, headers, cookies)
    """
    return metadata.parse_params(params, models)


def has_model(metadata: FunctionDecorator) -> bool:
    """
    return True if this function have
    :py:class:`spectree.model_adapter.ModelClass`
    """
    return metadata.has_model()


def parse_code(http_code: str) -> str:
    """
    get the code of this HTTP status

    :param str http_code: format like ``HTTP_200``
    """
    match = HTTP_CODE.match(http_code)
    if not match:
        return ""
    return match.group("code")


def parse_name(func: Callable[..., Any]) -> str:
    """
    the func can be

        * undecorated functions
        * decorated functions
        * decorated class methods
    """
    return func.__name__


def default_before_handler(
    req: Any,
    resp: Any,
    req_validation_error: Exception | None,
    instance: Any,
    model_adapter: ModelAdapterType,
):
    """
    default handler called before the endpoint function after the request validation

    :param req: request provided by the web framework
    :param resp: response generated by SpecTree that will be returned
        if the validation error is not None
    :param req_validation_error: request validation error
    :param instance: class instance if the endpoint function is a class method
    :param model_adapter: model adapter used by the current SpecTree instance
    """
    if req_validation_error:
        logger.error(
            "422 Request Validation Error: %s",
            model_adapter.validation_errors(req_validation_error),
        )


def default_after_handler(
    req: Any,
    resp: Any,
    resp_validation_error: Exception | None,
    instance: Any,
    model_adapter: ModelAdapterType,
):
    """
    default handler called after the response validation

    :param req: request provided by the web framework
    :param resp: response from the endpoint function (if there is no validation error)
        or response validation error
    :param resp_validation_error: response validation error
    :param instance: class instance if the endpoint function is a class method
    :param model_adapter: model adapter used by the current SpecTree instance
    """
    if resp_validation_error:
        logger.error(
            "500 Response Validation Error: %s",
            model_adapter.validation_errors(resp_validation_error),
        )


def hash_module_path(module_path: str):
    """
    generate short hash for module path to avoid the
    same name object defined in different Python files

    :param module_path: `str` module path
    """

    return sha1(module_path.encode()).hexdigest()[:7]


def get_model_key(model: ModelClass) -> str:
    """
    generate model name suffixed by short hashed path (instead of its path to
    avoid code-structure leaking)

    :param model: query, json, headers or cookies from request or response
    """

    def get_name(value: Any) -> str:
        origin = get_origin(value)
        if origin is Annotated:
            args = get_args(value)
            # Nested Annotated aliases are flattened by typing; the outermost
            # metadata appears last and should define the public schema name.
            for metadata in reversed(args[1:]):
                title = getattr(metadata, "title", None)
                if title:
                    return str(title)
            return get_name(args[0])
        if origin is list:
            args = get_args(value)
            item_name = get_name(args[0]) if args else "Any"
            return f"{item_name}List"
        return value.__name__

    model_name = get_name(model)
    module_path = model.__module__ if get_origin(model) is None else repr(model)
    return f"{model_name}.{hash_module_path(module_path=module_path)}"


def get_nested_key(parent: str, child: str) -> str:
    """
    generate nested model reference name suffixed by parent model name

    :param parent: string of parent name
    :param child: string of child name
    """

    return f"{parent}.{child}"


def get_security(security: Mapping | Sequence[Any] | None) -> list[Any]:
    """
    return the correct format of security
    """
    if security is None or not security:
        return []

    if isinstance(security, list):
        return security
    elif isinstance(security, dict):
        return [security]
    return []


def get_multidict_items(
    multidict: MultiDict, model: ModelClass | None = None
) -> dict[str, str | list[str] | None]:
    """
    return the items of a :class:`werkzeug.datastructures.ImmutableMultiDict`
    """
    res: dict[str, str | list[str] | None] = {}
    for key in multidict:
        values = multidict.getlist(key)
        if (model is not None and is_list_item(key, model)) or len(values) > 1:
            res[key] = multidict.getlist(key)
        else:
            res[key] = multidict.get(key)

    return res


def get_multidict_items_starlette(
    multidict: MultiDictStarlette, model: ModelClass | None = None
):
    """
    return the items of a :class:`starlette.datastructures.ImmutableMultiDict`
    """
    res = {}
    for key in multidict:
        values = multidict.getlist(key)
        if (model is not None and is_list_item(key, model)) or len(values) > 1:
            res[key] = values
        else:
            res[key] = multidict[key]

    return res


_REQUEST_ANNOTATION_NAMES = frozenset({"query", "json", "form", "headers", "cookies"})


def get_request_model_hints(func: Callable[..., Any]) -> Mapping[str, Any]:
    """Resolve annotations used by Spectree for request models.

    Only ``query``, ``json``, ``form``, ``headers``, and ``cookies``
    annotations are resolved. Return annotations and unrelated parameters
    are ignored so unresolved forward references in them do not affect
    request model processing.
    """
    annotations = getattr(func, "__annotations__", {})

    if not annotations:
        return {}

    if "return" not in annotations:
        selected_annotations = {
            name: annotation
            for name, annotation in annotations.items()
            if name in _REQUEST_ANNOTATION_NAMES
        }

        if not selected_annotations:
            return {}

        # Nothing has to be filtered out, so keep the original callable.
        # This is the fast path requested by the maintainer.
        if len(selected_annotations) == len(annotations):
            return get_type_hints(func, include_extras=True)
    else:
        selected_annotations = {
            name: annotation
            for name, annotation in annotations.items()
            if name in _REQUEST_ANNOTATION_NAMES
        }

        if not selected_annotations:
            return {}

    # We have to exclude either `return` or unrelated parameters.
    # Never mutate the original endpoint's __annotations__: decorators may
    # be invoked concurrently.
    proxy = FunctionType(
        func.__code__,
        func.__globals__,
        func.__name__,
        func.__defaults__,
        func.__closure__,
    )
    proxy.__annotations__ = selected_annotations

    if hasattr(func, "__kwdefaults__"):
        proxy.__kwdefaults__ = func.__kwdefaults__

    if hasattr(func, "__type_params__"):
        proxy.__type_params__ = func.__type_params__

    return get_type_hints(proxy, include_extras=True)


def is_list_item(key: str, model: ModelClass | None) -> bool:
    """Check if this key is a list item in the model."""
    if model is None:
        return False

    annotation = cached_type_hints(model).get(key)  # type: ignore
    if annotation is None:
        return False
    return _annotation_is_list(annotation)


def _annotation_is_list(annotation: Any) -> bool:
    origin = get_origin(annotation)
    if origin is list:
        return True
    if origin is Annotated:
        return _annotation_is_list(get_args(annotation)[0])
    if origin in (Union, UnionType):
        return any(
            arg is not type(None) and _annotation_is_list(arg)
            for arg in get_args(annotation)
        )
    return False


def parse_resp(
    metadata: FunctionDecorator, naming_strategy: NamingStrategy = get_model_key
):
    """
    get the response spec

    If this function does not have explicit ``resp`` but have other models,
    a ``422 Validation Error`` will be appended to the response spec, since
    this may be triggered in the validation step.
    """
    return metadata.parse_resp(naming_strategy)


def json_compatible_deepcopy(obj: Any) -> Any:
    """
    A custom deepcopy implementation that modifies the behavior of:

    Special numeric values will be replaced with their string representations.

    - `float("inf")` becomes `"Infinity"`
    - `float("-inf")` becomes `"-Infinity"`
    - `float("nan")` becomes `"NaN"`

    This is for compatibility with the general JSON spec, as defined in:

    - https://datatracker.ietf.org/doc/html/rfc7159.html

    This only works for the generated schema. It does not handle the recursive objects.
    DO NOT use this for other purposes.
    """

    def handle_float(x):
        if isnan(x):
            return "NaN"
        elif isinf(x):
            return "Infinity" if x > 0 else "-Infinity"
        return x

    _immutable_types = (int, float, bool, str, bytes, type(None))

    def naive_deepcopy(obj):
        """This does not handle the recursive objects."""
        cls = type(obj)
        if cls is dict:
            res = {
                naive_deepcopy(key): naive_deepcopy(value) for key, value in obj.items()
            }
        elif cls is list:
            res = [naive_deepcopy(item) for item in obj]
        elif cls is tuple:
            res = tuple(naive_deepcopy(item) for item in obj)
        elif cls is float:
            res = handle_float(obj)
        elif cls in _immutable_types:
            res = obj
        elif isinstance(obj, Enum):
            res = obj.value
        else:
            raise TypeError(f"Unsupported type for this custom deepcopy: {cls}")
        return res

    return naive_deepcopy(obj)
