blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://0b01001001.github.io/spectree/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/0b01001001/spectree/discussions
    about: Ask a question or start a discussion
